services:
  eddie:
    container_name: code_eddie
    image: codeserver:latest
    restart: unless-stopped
    environment:
      PASSWORD: eddie123
    volumes:
      - ./users/eddie:/home/coder/project
    ports:
      - "9001:8080"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G

  bob:
    container_name: code_bob
    image: codeserver:latest
    restart: unless-stopped
    environment:
      PASSWORD: bob123
    volumes:
      - ./users/bob:/home/coder/project
    ports:
      - "9002:8080"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G

  carol:
    container_name: code_carol
    image: codeserver:latest
    restart: unless-stopped
    environment:
      PASSWORD: carol123
    volumes:
      - ./users/carol:/home/coder/project
    ports:
      - "9003:8080"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G

  david:
    container_name: code_david
    image: codeserver:latest
    restart: unless-stopped
    environment:
      PASSWORD: david123
    volumes:
      - ./users/david:/home/coder/project
    ports:
      - "9004:8080"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G

networks:
  default:
    name: code_network
    driver: bridge