ignored:
  - DL3003  # Use WORKDIR to switch to a directory
  - DL3006  # Image last user should not be root
  - DL3008  # Pin versions in apt get install
  - DL3013  # Pin versions in pip install
  - DL3018  # Pin versions in apk add
  - DL3025  # Use absolute paths for FROM
  - DL3042  # Avoid cache directory with pip install
  - DL3059  # Multiple consecutive RUN instructions

trustedRegistries:
  - docker.io
  - gcr.io
  - registry.k8s.io
