services:
  vaultwarden-db:
    image: mariadb:11.8
    container_name: vaultwarden-db
    restart: always
    env_file:
      - .env
    volumes:
      - ./vaultwarden-db:/var/lib/mysql
      - ./vaultwarden-db/conf.d:/etc/mysql/conf.d
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    healthcheck:
      test: mariadb-admin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    hostname: vaultwarden
    depends_on:
      vaultwarden-db:
        condition: service_healthy
    restart: always
    env_file:
      - .env
    volumes:
      - ./vaultwarden:/data/
      - /etc/localtime:/etc/localtime:ro
    environment:
      DATABASE_URL: mysql://${MYSQL_USER}:${VAULTWARDEN_MYSQL_PASSWORD}@vaultwarden-db/${MYSQL_DATABASE}
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      RUST_BACKTRACE: 1
    ports:
      - "80:80"

volumes:
  vaultwarden:
  vaultwarden-db:
