services:
  teampass-web:
    image: dormancygrace/teampass:latest
    container_name: teampass-web
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: teampass.xiong-da.com   # 虛擬主機 IP 地址，用於反向代理配置（如果需要）
      VIRTUAL_PORT: 80
      DB_NAME: teampass-db           # MariaDB 資料庫名稱
      DB_USER: teampass_user         # MariaDB 資料庫使用者名稱
      DB_PASSWORD: <PASSWORD>        # MariaDB 資料庫密碼
      DB_HOST: mariadb_server        # 指定連接的資料庫主機為現有的 MariaDB 主機 IP 地址ort
    ports:
      - "12001:80"
    volumes:
      - ./teampass-html:/var/www/html  # 構建容器時掛載本地目錄到容器內部，以保存應用程式資料
      - ./vol1/1000/app/teampass/pass:/secured_path # 掛載安全路徑到 Teampass 容器
    networks:
      - mariadb_mariadb_net

networks:
  mariadb_mariadb_net:                      # 自定義網絡，使用橋接模式
    external: true                    # 指示這個網絡是外部創建並已存在於 Docker 中的