services:
  electerm-web:
    container_name: electerm-web
    environment:
      - DB_PATH=/home/electerm/data
      - HOST=0.0.0.0
      - SERVER_SECRET=256位元隨機字串
      - SERVER_PASS=登入密碼
      - ENABLE_AUTH=1
      - TZ=Asia/Taipei
    image: zxdong262/electerm-web:latest
    init: True
    ports:
      - '18082:5577'
    volumes:
      - /mnt/Storage/app/electerm-web:/home/electerm/data
    restart: unless-stopped
