services:
  nginx-ui:
    image: uozi/nginx-ui:dev
    container_name: nginx-ui
    restart: unless-stopped
    networks:
      - nginx-ui-network
    environment:
      - NGINX_UI_NODE_DEMO=true
      - NGINX_UI_SERVER_HOST=0.0.0.0
      - NGINX_UI_SERVER_PORT=9168
      - NGINX_UI_NGINX_CONFIG_DIR=/etc/nginx
      - NGINX_UI_AUTH_MAX_ATTEMPTS=5
    ports:
      - 80:80
      - 443:443
      - 9168:9168
    volumes:
      - /opt/stacks/nginx-ui/configs/app.ini:/etc/nginx-ui/app.ini:rc
      - ./nginx-ui/nginx-ui-data:/etc/nginx-ui
      - ./nginx-ui/logs:/var/log/nginx
      - ./nginx-ui/run:/var/run
      - /etc/localtime:/etc/localtime:ro
      - /etc/nginx/geoip:/etc/nginx/geoip
      - /etc/nginx/modules:/etc/nginx/modules
      - /etc/nginx/ssl:/etc/nginx/ssl
      - /etc/nginx/conf.d:/etc/nginx/conf.d
      - /etc/nginx/modsecurity:etc/nginx/modsecurity
      - /usr/lib/nginx/modules:/usr/lib/nginx/modules
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  nginx-ui-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: "true"






