services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql2022-dev
    environment:
      - ACCEPT_EULA= Y
      - MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
      - MSSQL_PID: "Developer"
      - MSSQL_COLLATION: "Chinese_Taiwan_Stroke_Count_100_CI_AS_SC_UTF8"
      - MSSQL_AGENT_ENABLED: "true"
      - TZ: "Asia/Taipei"
    ports:
      - "1433:1433"
    volumes:
      - /mnt/Storage/app/mssql/sql_data:/var/opt/mssql
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "${MSSQL_SA_PASSWORD}", "-Q", "SELECT 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
