version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql2022-dev
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD} # 務必使用強密碼，從 .env 讀取
      - MSSQL_PID=Developer
      - TZ=Asia/Taipei 
    ports:
      - "1433:1433"
    volumes:
      - ./sql_data:/var/opt/mssql
    restart: always
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "${MSSQL_SA_PASSWORD}", "-Q", "SELECT 1" ]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  sql_data: