version: "3.9"

services:
  base: &base
    image: chatwoot/chatwoot:latest
    env_file: .env
    volumes:
      - ./storage_data:/app/storage

  rails:
    <<: *base
    container_name: chatwoot_rails
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    entrypoint: docker/entrypoints/rails.sh
    command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]
    restart: always

