version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: chatwoot_postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Asia/Taipei
    ports:
      - "5432:5432"
    volumes:
      - /vol1/1000/app/postgres/pgdata:/var/lib/postgresql/data
    # --- 添加健康檢查設定 ---
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s # 每 10 秒執行一次檢查
      timeout: 5s   # 檢查超時時間
      retries: 5    # 重試 5 次失敗後標記為不健康
      start_period: 30s # 容器啟動後的初始化等待時間