version: '3.8'
services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "9379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]  
    volumes:
      - ./redis_data:/data  
    